travis:
  secure:
    BINSTAR_TOKEN: FlfzHHOonMkfL/IZvnaMaooRuua25o9MFhj8x2v4l5bmnBkKSGU52Q97jICHpufbYiYdXMA0Pz/8zej3U5E5fDu8YKCfGn1n7pBrQqzlOCFVFzD47kBlX8NFIJT1IprbZkEvBZ52+S7qgEw+lZ7vtaBqx+XBSHaqg8uSnFfraAYE8t2K73DpCSYk2zucTyRv3rK0ll3A9qkR7h70tXf0X5YyLsKYYirEIxFSSvtqwaEx0sASKb02e1xflRGdWrZSmzlH/ISb0lgNo7D+NNRevGNfyGf732OPuirfr3ae0axoiBQi4Vk989KDqWPk1JdKXpyiBvID5ExF6eTXf0BWXihZQc6cR0FBJaLhOoZY1dTk/EfHAUZfYzYO0TRXYlXBfoDAu6570gpknYfZgG1AYYrQMq4hQUDY0KKd/SQOgn4xBaQ+ydIO9lgEQ+cHZZ9UTYObwnnjZ6nN3VIzTqC9v1YXRRIJy22T8QVRtDj/m3ZpBUVBH9n3uwpnqiIYG2xuqC5pKx342waXZLdzjRMura1KTXNac7KWAPhs3txbnqx/H1H2wDLSloO4rVEu5sXXfcOtVNl32muVHuc9git6BoH0KO0UyZKC04u/o1RKbffU4PjDaBoCdi2tv7k/SQ5soLpRCko//2fHBaYpr4MvJ/80wfx25T0gI+PETh873Sw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
